# Generated by Django 4.2.3 on 2023-07-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
