# Generated by Django 4.2.3 on 2023-07-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_personnel_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
