# Generated by Django 4.2.3 on 2023-07-21 20:41

from django.db import migrations, models
import django.db.models.deletion
import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_personnel_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_of_origin', models.CharField(max_length=100)),
                ('local_gov_area', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[personnel.models.validate_phone_number_length])),
                ('service_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel')),
            ],
        ),
    ]
